# Builder stage
FROM docker.io/library/golang:1.22-alpine as builder

# Install make
RUN apk update && apk add make

# Copy the source code from the host to the container
COPY pkg /workdir/app/pkg
COPY tools /workdir/app/tools
COPY cmd /workdir/app/cmd
COPY vendor /workdir/app/vendor
COPY go.mod /workdir/app/go.mod
COPY go.sum /workdir/app/go.sum
COPY Makefile /workdir/app/Makefile

WORKDIR /workdir/app

RUN make kubevirt-api-lifecycle-automation

# Final stage
FROM docker.io/library/golang:1.22-alpine

# Copy the binary from the builder stage to the final image
COPY --from=builder /workdir/app/kubevirt_api_lifecycle_automation /app/kubevirt_api_lifecycle_automation

# Set the working directory to /app
WORKDIR /app

# Add a non-root user for running the application
RUN adduser -u 1001 -D -s /bin/sh -h /app/kubevirt_api_lifecycle_automation kubevirt_api_lifecycle_automation
USER 1001

# Set the entrypoint to the binary
ENTRYPOINT ["/app/kubevirt_api_lifecycle_automation"]